# Generated by Django 5.1.3 on 2024-12-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
