# Generated by Django 5.1.3 on 2024-12-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_rsvp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSVP',
        ),
    ]
