# Generated by Django 5.1.3 on 2024-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_delete_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(choices=[('Orchid Ballroom', 'The Orchid Ballroom'), ('Grand Oak', 'Grand Oak Banquet'), ('Lotus Hall', 'Lotus Event Hall'), ('Royal Crown', 'The Royal Crown'), ('Blue Pearl', 'Blue Pearl Pavilion')], default='Orchid Ballroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(max_length=15),
        ),
    ]
